// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Regulariza - Destravar seu imóvel nunca foi tão fácil",
  description: "Plataforma inteligente para regularização de imóveis com IA. Simplifique o processo de regularização da sua propriedade.",
  keywords: "regularização de imóveis, documentação de imóveis, escritura, IPTU, usucapião",
  authors: [{ name: "Regulariza" }],
  openGraph: {
    title: "Regulariza - Destravar seu imóvel nunca foi tão fácil",
    description: "Plataforma inteligente para regularização de imóveis com IA",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5" />
        <meta name="theme-color" content="#0D0D0D" />
      </head>
      <body
        className={`${inter.variable} antialiased bg-[#0D0D0D] text-white min-h-screen`}
        style={{ fontFamily: 'Inter, system-ui, sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}
